apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        version: v1
    spec:
      containers:
      - name: api-gateway
        image: adiselv/captivate.api-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name : KAFKA_SERVER
            value : kafka-service:9092
        
